# Generated by Django 4.2.10 on 2024-06-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamleadAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('enddate', models.DateField(blank=True, max_length=100, null=True)),
                ('task_description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_teamlead': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('employeename', models.CharField(max_length=100)),
                ('projectdate', models.DateField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.teamleadassign')),
            ],
        ),
    ]
