# Generated by Django 3.2.25 on 2024-05-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamleadAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('enddate', models.DateField(blank=True, max_length=100, null=True)),
                ('task_description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
        ),
    ]
