# Generated by Django 4.2.10 on 2024-06-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAssign',
        ),
    ]
