# Generated by Django 3.2.25 on 2024-06-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_is_admin_user_is_hr'),
        ('hrapp', '0002_studentassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleadassign',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_teamlead': True}, on_delete=django.db.models.deletion.CASCADE, to='authapp.user'),
        ),
    ]
