# Generated by Django 3.2.25 on 2024-06-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_is_admin_user_is_hr'),
        ('hrapp', '0005_studentassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassign',
            name='guide_name',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='authapp.user', to_field='username'),
        ),
        migrations.AlterField(
            model_name='studentassign',
            name='student_name',
            field=models.ForeignKey(limit_choices_to={'is_intern': True}, on_delete=django.db.models.deletion.CASCADE, to='authapp.user', to_field='username'),
        ),
    ]
