# Generated by Django 3.2.25 on 2024-06-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_is_admin_user_is_hr'),
        ('hrapp', '0006_auto_20240607_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('enddate', models.DateField(blank=True, max_length=100, null=True)),
                ('staff_name', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='authapp.user', to_field='username')),
            ],
        ),
    ]
