# Generated by Django 3.2.25 on 2024-06-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_is_admin_user_is_hr'),
        ('hrapp', '0007_staffassign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffAssign',
            new_name='ProjectAssign',
        ),
    ]
