# Generated by Django 4.2.10 on 2024-06-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0008_alter_studentassign_guide_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAssign',
        ),
    ]
