# Generated by Django 4.2.10 on 2024-06-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0010_studentassign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAssign',
        ),
    ]
