# Generated by Django 3.2.25 on 2024-06-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0011_leaveform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveForm',
        ),
    ]
