# Generated by Django 3.2.25 on 2024-06-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_delete_projectassign'),
        ('hrapp', '0013_leave'),
    ]

    operations = [
    ]
