# Generated by Django 3.2.25 on 2024-06-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_user_is_user'),
        ('hrapp', '0014_merge_0002_delete_projectassign_0013_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, max_length=100, null=True)),
                ('enddate', models.DateField(blank=True, max_length=100, null=True)),
                ('staff_name', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='authapp.user', to_field='username')),
            ],
        ),
    ]
