# Generated by Django 4.2.10 on 2024-06-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0014_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='duration_days',
            field=models.IntegerField(),
        ),
    ]
