# Generated by Django 4.2.10 on 2024-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0015_alter_leave_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
