# Generated by Django 4.2.10 on 2024-06-14 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0016_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='candidate',
            field=models.ForeignKey(default=1, limit_choices_to='username', on_delete=django.db.models.deletion.CASCADE, related_name='leave_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
