# Generated by Django 4.2.10 on 2024-06-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0022_leave_name_alter_leave_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
