# Generated by Django 4.2.10 on 2024-06-15 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0023_alter_leave_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='candidate',
        ),
        migrations.AlterField(
            model_name='leave',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
