# Generated by Django 4.2.10 on 2024-06-20 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0030_alter_leave_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassign',
            name='time_slot',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
