# Generated by Django 5.0.6 on 2024-06-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0031_studentassign_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassign',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
