# Generated by Django 4.2.10 on 2024-06-22 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0032_noteupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignproject',
            name='projectname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StatusShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('note_upload', models.FileField(upload_to='uploads/')),
                ('Teamleadname', models.ForeignKey(limit_choices_to={'is_teamlead': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_shares', to='hrapp.assignproject', to_field='projectname')),
            ],
        ),
    ]
