# Generated by Django 4.2.10 on 2024-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0033_alter_assignproject_projectname_statusshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('Firm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_spend', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
