# Generated by Django 4.2.10 on 2024-06-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0034_digitaltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mode_of_work', models.CharField(blank=True, choices=[('work from home', 'work from home'), ('work from office', 'work from office')], default='work from office', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, choices=[('0 year', '0 year'), ('1 year', '1 year'), ('2 years', '2 years'), ('more than 2 years', 'more than 2 years')], max_length=100, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
