# Generated by Django 5.0.6 on 2024-06-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0033_assignproject_status'),
        ('hrapp', '0035_jobapply'),
    ]

    operations = [
    ]
