# Generated by Django 4.2.10 on 2024-06-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0035_jobapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='callsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
