# Generated by Django 4.2.10 on 2024-06-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0036_callsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='quatation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('add_on', models.DateField(blank=True, max_length=100, null=True)),
                ('expired_on', models.DateField(blank=True, max_length=100, null=True)),
                ('quatation_type', models.CharField(choices=[('web_app_development', 'Web App Development'), ('mobile_app_development', 'Mobile App Development'), ('digital_marketing', 'Digital Marketing')], default='web_app_development', max_length=50)),
                ('development_charge', models.IntegerField(blank=True, max_length=100, null=True)),
                ('gst_amount', models.FloatField(blank=True, max_length=100, null=True)),
                ('total_amount', models.FloatField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
