# Generated by Django 4.2.10 on 2024-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0037_quatation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quatation',
            name='development_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
