# Generated by Django 4.2.10 on 2024-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0038_alter_quatation_development_charge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quatation',
            new_name='quotation',
        ),
    ]
