# Generated by Django 5.0.6 on 2024-06-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0036_merge_0033_assignproject_status_0035_jobapply'),
        ('hrapp', '0039_rename_quatation_quotation'),
    ]

    operations = [
    ]
