# Generated by Django 5.0.6 on 2024-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0040_merge_20240622_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignproject',
            name='projectname',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='experience',
            field=models.CharField(blank=True, choices=[('0 year', '0 year'), ('1 year', '1 year'), ('2 years', '2 years'), ('more than 2 years', 'more than 2 years')], default='0 year', max_length=100, null=True),
        ),
    ]
