# Generated by Django 4.2.10 on 2024-06-28 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_merge_20240622_1453'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0041_alter_assignproject_projectname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAllocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.IntegerField(unique=True)),
                ('vacate', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile')),
                ('student', models.ForeignKey(limit_choices_to={'is_intern': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.studentassign')),
            ],
        ),
    ]
