# Generated by Django 4.1 on 2024-07-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0044_rename_mode_of_work_jobapply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='status',
            field=models.CharField(blank=True, choices=[('work from home', 'work from home'), ('work from office', 'work from office')], max_length=100, null=True),
        ),
    ]
