# Generated by Django 4.1 on 2024-07-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0045_alter_jobapply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapply',
            old_name='status',
            new_name='mode_of_work',
        ),
    ]
