# Generated by Django 4.1 on 2024-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0046_rename_status_jobapply_mode_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='mode_of_work',
            field=models.CharField(blank=True, choices=[('work from home', 'Work from Home'), ('work from office', 'Work from Office')], max_length=100, null=True),
        ),
    ]
