# Generated by Django 4.1 on 2024-07-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0047_alter_jobapply_mode_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='mode_of_work',
            field=models.CharField(blank=True, choices=[('Work from Home', 'Work from Home'), ('Work from Office', 'Work from Office')], max_length=100, null=True),
        ),
    ]
