# Generated by Django 4.1 on 2024-07-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_rename_degree_program_userprofile_course_and_more'),
        ('hrapp', '0048_alter_jobapply_mode_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_courses', to='authapp.userprofile', to_field='course'),
        ),
    ]
