# Generated by Django 4.1 on 2024-07-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0049_alter_machineallocate_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusshare',
            old_name='projct_name',
            new_name='project_name',
        ),
    ]
