# Generated by Django 4.1 on 2024-07-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0050_rename_projct_name_statusshare_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsheet',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='start_date',
        ),
    ]
