# Generated by Django 4.1 on 2024-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0051_rename_end_date_callsheet_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocate',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
