# Generated by Django 4.1 on 2024-11-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapp', '0052_alter_machineallocate_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusshare',
            name='Teamleadname',
            field=models.ForeignKey(limit_choices_to={'is_teamlead': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
