# Generated by Django 4.2.10 on 2024-06-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_is_admin_user_is_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
    ]
