# Generated by Django 4.2.10 on 2024-06-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_userprofile_intership_type_and_more'),
        ('authapp', '0009_alter_user_image'),
    ]

    operations = [
    ]
