# Generated by Django 5.0.6 on 2024-06-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_userprofile_intership_type_and_more'),
        ('authapp', '0009_alter_user_image'),
    ]

    operations = [
    ]
