# Generated by Django 5.0.6 on 2024-06-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_merge_20240621_1624'),
        ('authapp', '0010_merge_20240622_0954'),
    ]

    operations = [
    ]
