# Generated by Django 5.0.6 on 2024-06-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_merge_20240622_1257'),
        ('authapp', '0012_feedback_testimonial'),
    ]

    operations = [
    ]
