# Generated by Django 4.2.10 on 2024-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_merge_20240622_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree_program',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
