# Generated by Django 4.1 on 2024-07-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_userprofile_degree_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='degree_program',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='internship_position',
            new_name='educationalQualification',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university',
        ),
    ]
