# Generated by Django 4.1 on 2024-07-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_rename_degree_program_userprofile_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='educationalQualification',
            new_name='degree_program',
        ),
    ]
