# Generated by Django 4.1 on 2024-07-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_rename_educationalqualification_userprofile_degree_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='degree_program',
            new_name='educationqualification',
        ),
    ]
