# Generated by Django 4.1 on 2024-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
